# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# |         Bedwars1058 Map           |
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
sound:
    play-map-sound: "NOTE_PLING;10;2"
    play-notmap-sound: "NOTE_PLING;10;2"